name: flutter_touch_spin
description: Simple number input spinner Widget for Flutter. Inspired by Bootstrap Touchspin
version: 1.0.0
author: Danvick Miller <danvickmiller@gmail.com>
homepage: https://github.com/danvick/flutter_touch_spin

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

